export const charactersDetails as CharacterType = [
    {
        image: 'Jaime_luchador.webp',
        name: 'Jaime Lannister',
        family: 'Lannister',
        age: 34,
        sentence: 'Primero pego y luego pregunto',
        emoji: '&#9876',
        weapon: 'espadaca',
        skills: 27,
    },
    {
        image: 'Tyrion_asesor_Dae.webp',
        name: 'Tyrion Lannister',
        family: 'Targaryen',
        age: 27,
        sentence: 'No sé por qué, pero creo que voy a morir pronto',
        emoji: '&#127891',
        master: 'Daenerys Targaryen',
    },
    {
        image: 'Joffrey_rey.webp',
        name: 'Joffrey Baratheon',
        family: 'Lannister',
        age: 14,
        sentence: 'Vais a morir todos',
        emoji: '&#128081',
        yearsService: 2,
    },
    {
        image: 'Daenerys_luchadora.webp',
        name: 'Daenerys Targaryen',
        family: 'Targaryen',
        age: 16,
        sentence: 'Primero pego y luego pregunto',
        emoji: '&#9876',
        weapon: 'dragons',
        skills: 55,
    },
    {
        image: 'Bronn_escudero_Jai.webp',
        name: 'Bronn',
        family: 'Lannister',
        age: 32,
        sentence: 'Soy un loser',
        emoji: '&#128737',
        master: 'Jaime Lannister',
        ballLevel: 7,
    },
];
